theme: jekyll-theme-slate 
title: Welcome to the homepage of YUYuxuan
description: 🍻How lucky we are to be alive right now!
plugins: 
    - jemoji 
url: "https://reon0330.github.io/" 
markdown: kramdown
